import React, { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import { Search, Star, Filter, Lightbulb, TrendingUp, BookOpen, Heart, ShoppingBag, Cpu, Globe } from 'lucide-react';
import { Link } from 'react-router-dom';

const CATS = ['All', 'AI', 'SaaS', 'EdTech', 'Health', 'Fintech', 'Marketplace'];

const IDEAS = [
  { id: 1,  title: 'AI Study Planner for Competitive Exams',      score: 87, category: 'EdTech',      description: 'Personalized daily study schedules generated by AI based on syllabus gaps, past performance, and exam date.', tags: ['AI', 'Students'] },
  { id: 2,  title: 'Micro-SaaS Invoice Automation for Freelancers', score: 82, category: 'SaaS',      description: 'Automatically generate, send, and follow up on invoices via WhatsApp and email with zero manual effort.', tags: ['Automation', 'SMB'] },
  { id: 3,  title: 'Mental Health Check-In App for Remote Teams',  score: 79, category: 'Health',     description: 'Weekly mood pulse with anonymous team heatmaps, manager nudges, and AI-generated wellness action plans.', tags: ['Wellness', 'HR'] },
  { id: 4,  title: 'Hyperlocal Skill-Swap Marketplace',            score: 76, category: 'Marketplace', description: 'Exchange skills with neighbors — coding for cooking, design for plumbing — no money involved.', tags: ['Community', 'Gig'] },
  { id: 5,  title: 'AI Legal Document Simplifier',                 score: 91, category: 'AI',          description: 'Upload any contract or legal document; receive plain-English summaries and flagged risk clauses in seconds.', tags: ['LegalTech', 'AI'] },
  { id: 6,  title: 'Personalized Nutrition Coach via WhatsApp',    score: 73, category: 'Health',     description: 'Users log meals by photo or text; AI responds with macro tracking, meal swaps, and weekly reports.', tags: ['Health', 'AI'] },
  { id: 7,  title: 'B2B SaaS Pricing Intelligence Tool',           score: 85, category: 'SaaS',       description: 'Track competitor pricing changes in real-time and receive alerts when market rates shift in your vertical.', tags: ['Analytics', 'B2B'] },
  { id: 8,  title: 'College Student Expense Split App',            score: 68, category: 'Fintech',    description: 'Simplified expense splitting designed for hostels and PGs — no credit cards required, UPI-native.', tags: ['Students', 'Finance'] },
  { id: 9,  title: 'AI-Powered Code Review Bot for GitHub',        score: 88, category: 'AI',         description: 'Automated PR reviews with context-aware suggestions, security scanning, and style enforcement in one bot.', tags: ['DevTools', 'AI'] },
  { id: 10, title: 'On-Demand Home Services for Tier-2 Cities',    score: 71, category: 'Marketplace', description: 'Booking platform for electricians, plumbers, and cleaners in under-served metros with verified profiles.', tags: ['Home', 'Local'] },
  { id: 11, title: 'EdTech for Vernacular Language Learners',      score: 77, category: 'EdTech',     description: 'Interactive lessons in regional Indian languages using voice AI and gamified exercises.', tags: ['Education', 'Regional'] },
  { id: 12, title: 'AI CFO for Early-Stage Startups',              score: 83, category: 'Fintech',    description: 'Automated cashflow forecasting, burn rate alerts, and fundraising readiness report for founders.', tags: ['Finance', 'Startup'] },
];

// Icons as a component so JSX always runs inside React scope
function CatIcon({ category }) {
  if (category === 'AI')          return <Cpu className="w-3.5 h-3.5" />;
  if (category === 'SaaS')        return <Globe className="w-3.5 h-3.5" />;
  if (category === 'EdTech')      return <BookOpen className="w-3.5 h-3.5" />;
  if (category === 'Health')      return <Heart className="w-3.5 h-3.5" />;
  if (category === 'Fintech')     return <TrendingUp className="w-3.5 h-3.5" />;
  if (category === 'Marketplace') return <ShoppingBag className="w-3.5 h-3.5" />;
  return <Lightbulb className="w-3.5 h-3.5" />;
}

const CAT_COLORS = {
  AI:          'text-violet-600 dark:text-violet-400 bg-violet-50 dark:bg-violet-900/30 border-violet-200 dark:border-violet-700/40',
  SaaS:        'text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 border-blue-200 dark:border-blue-700/40',
  EdTech:      'text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/30 border-indigo-200 dark:border-indigo-700/40',
  Health:      'text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/30 border-rose-200 dark:border-rose-700/40',
  Fintech:     'text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-900/30 border-emerald-200 dark:border-emerald-700/40',
  Marketplace: 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/30 border-amber-200 dark:border-amber-700/40',
};

function ScoreRing({ score }) {
  const color = score >= 85 ? '#22c55e' : score >= 70 ? '#f59e0b' : '#ef4444';
  const label = score >= 85 ? 'Strong' : score >= 70 ? 'Average' : 'Weak';
  return (
    <div className="flex flex-col items-center gap-1">
      <div
        className="w-14 h-14 rounded-full flex items-center justify-center font-extrabold text-lg"
        style={{ background: `conic-gradient(${color} ${score * 3.6}deg, #e2e8f0 0deg)` }}
      >
        <div className="w-10 h-10 rounded-full bg-white dark:bg-slate-800 flex items-center justify-center">
          <span className="text-xs font-bold" style={{ color }}>{score}</span>
        </div>
      </div>
      <span className="text-xs font-semibold" style={{ color }}>{label}</span>
    </div>
  );
}

function IdeaCard({ idea, index }) {
  const catColor = CAT_COLORS[idea.category] || '';

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: index * 0.04 }}
      className="group bg-white dark:bg-slate-800/70 border border-slate-200 dark:border-slate-700/50 rounded-2xl p-5 hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300"
    >
      <div className="flex items-start justify-between gap-3 mb-4">
        <div className="flex-1 min-w-0">
          <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full border text-xs font-semibold mb-2 ${catColor}`}>
            <CatIcon category={idea.category} />
            {idea.category}
          </span>
          <h3 className="text-slate-900 dark:text-white font-semibold text-sm leading-snug group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">
            {idea.title}
          </h3>
        </div>
        <ScoreRing score={idea.score} />
      </div>
      <p className="text-slate-500 dark:text-slate-400 text-xs leading-relaxed mb-4 line-clamp-2">{idea.description}</p>
      <div className="flex flex-wrap gap-1.5">
        {idea.tags.map(tag => (
          <span key={tag} className="px-2 py-0.5 text-xs rounded-md bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 font-medium">
            #{tag}
          </span>
        ))}
      </div>
    </motion.div>
  );
}

export function ExploreIdeasPage() {
  const [activeCategory, setActiveCategory] = useState('All');
  const [query, setQuery] = useState('');
  const [sortBy, setSortBy] = useState('score');

  const filtered = useMemo(() => {
    let list = IDEAS.filter(n => {
      const matchCat = activeCategory === 'All' || n.category === activeCategory;
      const q = query.toLowerCase();
      const matchQ = !q || n.title.toLowerCase().includes(q) || n.description.toLowerCase().includes(q);
      return matchCat && matchQ;
    });
    if (sortBy === 'score') list = [...list].sort((a, b) => b.score - a.score);
    return list;
  }, [activeCategory, query, sortBy]);

  return (
    <div className="relative min-h-screen bg-slate-50 dark:bg-[#050508]">
      {/* Header */}
      <section className="py-16 border-b border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900/40">
        <div className="container mx-auto px-4 max-w-5xl text-center">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-50 dark:bg-primary-900/30 border border-primary-200 dark:border-primary-700/50 text-primary-700 dark:text-primary-300 text-xs font-bold tracking-widest uppercase mb-5"
          >
            <Lightbulb className="w-3.5 h-3.5" />
            Community Validated
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.07 }}
            className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white mb-4 tracking-tight"
          >
            Explore Ideas
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.14 }}
            className="text-slate-500 dark:text-slate-400 text-lg max-w-xl mx-auto"
          >
            Browse validated startup ideas across categories. Get inspired — then build.
          </motion.p>
        </div>
      </section>

      {/* Filters */}
      <div className="sticky top-16 z-20 bg-white/90 dark:bg-slate-900/80 backdrop-blur-md border-b border-slate-100 dark:border-slate-800">
        <div className="container mx-auto px-4 max-w-5xl py-3 flex flex-col sm:flex-row items-center gap-3">
          <div className="relative flex-1 w-full">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="text"
              placeholder="Search ideas..."
              value={query}
              onChange={e => setQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 text-sm rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-primary-500/40"
            />
          </div>
          <div className="flex items-center gap-2 flex-shrink-0 flex-wrap justify-center">
            {CATS.map(cat => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                  activeCategory === cat
                    ? 'bg-primary-500 border-primary-500 text-white shadow-sm'
                    : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:border-primary-400 hover:text-primary-600'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 max-w-5xl py-12">
        <div className="flex items-center justify-between mb-6">
          <p className="text-slate-500 dark:text-slate-400 text-sm">{filtered.length} ideas found</p>
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-slate-400" />
            <select
              value={sortBy}
              onChange={e => setSortBy(e.target.value)}
              className="text-sm border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-1.5 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 focus:outline-none"
            >
              <option value="score">Sort by Score</option>
              <option value="default">Default</option>
            </select>
          </div>
        </div>

        {filtered.length === 0 ? (
          <div className="text-center py-24 text-slate-400 dark:text-slate-500">
            <Lightbulb className="w-10 h-10 mx-auto mb-4 opacity-40" />
            <p className="text-lg font-medium">No ideas match your search.</p>
          </div>
        ) : (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {filtered.map((idea, i) => <IdeaCard key={idea.id} idea={idea} index={i} />)}
          </div>
        )}

        <div className="mt-12 text-center">
          <p className="text-slate-500 dark:text-slate-400 mb-4">Have your own idea?</p>
          <Link
            to="/submit"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary-500 hover:bg-primary-600 text-white font-semibold text-sm transition-colors shadow-sm"
          >
            <Lightbulb className="w-4 h-4" />
            Validate Your Idea Free
          </Link>
        </div>
      </div>
    </div>
  );
}
